version: '3.8'
services:
  mariadb:
    init: true
    container_name : mariadb
    build :
      context : ./requirements/mariadb
      dockerfile : Dockerfile
      args :
        - MDB_ROOT_PASSWORD=${MDB_ROOT_PASSWORD}
        - MDB_DATABASE=${MDB_DATABASE}
        - MDB_USER=${MDB_USER}
        - MDB_PASSWORD=${MDB_PASSWORD}
    volumes :
      - mariadb:/var/lib/mysql
    restart : always
    networks:
      - inception
  wordpress:
    init: true
    container_name : wordpress
    depends_on : 
      - mariadb
    environment :
        - MDB_ROOT_PASSWORD=${MDB_ROOT_PASSWORD}
        - MDB_DATABASE=${MDB_DATABASE}
        - MDB_USER=${MDB_USER}
        - MDB_PASSWORD=${MDB_PASSWORD}
        - MDB_HOST=${MDB_HOST}
        - WP_URL=${WP_URL}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
    build :
      context : ./requirements/wordpress
      dockerfile : Dockerfile
    volumes :
      - wordpress:/var/www/html
    restart : always
    networks:
      - inception
  nginx:
    init: true
    container_name : nginx
    depends_on:
      - wordpress
    build :
      context : ./requirements/nginx
      dockerfile : Dockerfile
    volumes :
      - wordpress:/var/www/html
    ports :
      - "443:443"
    restart : always
    networks:
      - inception
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_PATH}mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_PATH}wordpress
      o: bind
networks:
  inception:
    driver: bridge