version : '3.8'
services :
  mariadb :
    container_name : mariadb

    build :
      context : ./mariadb
      dockerfile : Dockerfile
      args :
        - MDB_ROOT_PASSWORD=${MDB_ROOT_PASSWORD}
        - MDB_DATABASE=${MDB_DATABASE}
        - MDB_USER=${MDB_USER}
        - MDB_PASSWORD=${MDB_PASSWORD}
    volumes :
      - ./mariadb/content:/var/lib/mysql
    restart : always
    networks:
      - inception
  wordpress :
    init: true
    container_name : wordpress
    depends_on : 
      - mariadb
    environment :
        - MDB_ROOT_PASSWORD=${MDB_ROOT_PASSWORD}
        - MDB_DATABASE=${MDB_DATABASE}
        - MDB_USER=${MDB_USER}
        - MDB_PASSWORD=${MDB_PASSWORD}
        - MDB_HOST=${MDB_HOST}
    build :
      context : ./wordpress
      dockerfile : Dockerfile
    volumes :
      - ./wordpress/content:/var/www/html
    ports :
      - "3306:3306"
    restart : always
    networks:
      - inception
  nginx:
    container_name : nginx
    build :
      context : ./nginx
      dockerfile : Dockerfile
    volumes :
      - ./wordpress/content:/var/www/html
    ports :
      - "443:443"
    restart : always
    networks:
      - inception
networks:
  inception:
    driver: bridge